name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.21
        id: go

      - name: Set up linter
        run: go install github.com/mgechev/revive@latest

      - name: Get dependencies
        run: go mod download

      - name: Lint
        run: revive -config revive.toml -formatter stylish -exclude ./vendor/... ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
